argocd-apps:
  applications:
    - name: app-of-app
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      finalizers: []
      project: default
      source:
        repoURL: https://github.com/thirtynine96/argo-app-of-apps.git
        targetRevision: HEAD
        path: argo-apps
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas
      info:
      - name: url
        value: https://argoproj.github.io/