apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thirtynine96/declarative-argocd.git
    targetRevision: HEAD
    path: service-applications/guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: env-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
