apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
  finalizers: []
spec:
  destination:
    namespace: env-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: service-applications/helm-guestbook
    repoURL: https://github.com/thirtynine96/argo-app-of-apps
    targetRevision: HEAD
